// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo1LuXkwlXtBM4zxO1z65-oYGAgLqI0ZI',
    appId: '1:1026557559846:web:1befa3abfaefc09e6a52e7',
    messagingSenderId: '1026557559846',
    projectId: 'fuelgo-62663',
    authDomain: 'fuelgo-62663.firebaseapp.com',
    storageBucket: 'fuelgo-62663.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiiRGThi-J-5Mi3X8KYCjN233DnVDjD88',
    appId: '1:1026557559846:android:cb1e2344f6f24ca46a52e7',
    messagingSenderId: '1026557559846',
    projectId: 'fuelgo-62663',
    storageBucket: 'fuelgo-62663.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAMsqRp2KFGAVscHFnRZt9_MVOnwKfW14',
    appId: '1:1026557559846:ios:6b711d86ebbd4b0e6a52e7',
    messagingSenderId: '1026557559846',
    projectId: 'fuelgo-62663',
    storageBucket: 'fuelgo-62663.firebasestorage.app',
    iosBundleId: 'com.example.fuelgoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAMsqRp2KFGAVscHFnRZt9_MVOnwKfW14',
    appId: '1:1026557559846:ios:6b711d86ebbd4b0e6a52e7',
    messagingSenderId: '1026557559846',
    projectId: 'fuelgo-62663',
    storageBucket: 'fuelgo-62663.firebasestorage.app',
    iosBundleId: 'com.example.fuelgoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBo1LuXkwlXtBM4zxO1z65-oYGAgLqI0ZI',
    appId: '1:1026557559846:web:0df74096355407d96a52e7',
    messagingSenderId: '1026557559846',
    projectId: 'fuelgo-62663',
    authDomain: 'fuelgo-62663.firebaseapp.com',
    storageBucket: 'fuelgo-62663.firebasestorage.app',
  );
}
